package io.kyouin.jarknights.enums;

public enum ItemType {

    ACTIVITY_COIN, ACTIVITY_ITEM, AP_BASE, AP_GAMEPLAY, AP_ITEM, AP_SUPPLY,
    CARD_EXP, DIAMOND, DIAMOND_SHD, EXP_PLAYER, GOLD, HGG_SHD, LGG_SHD, MATERIAL, SOCIAL_PT,
    TKT_GACHA, TKT_GACHA_10, TKT_GACHA_PRSV, TKT_INST_FIN, TKT_RECRUIT, TKT_TRY, VOUCHER_PICK
}
