package io.kyouin.jarknights.enums;

public enum VoicePlaceType {

    BATTLE_FACE_ENEMY, BATTLE_PLACE, BATTLE_SELECT, BATTLE_SKILL_1, BATTLE_SKILL_2, BATTLE_SKILL_3, BATTLE_SKILL_4, BATTLE_START,
    BUILDING_FAVOR_BUBBLE, BUILDING_PLACE, BUILDING_TOUCHING, EVOLVE_ONE, EVOLVE_TWO, FOUR_STAR, GACHA, GREETING,
    HOME_PLACE, HOME_SHOW, HOME_WAIT, LEVEL_UP, LOADING_PANEL, LOSE, SQUAD, SQUAD_FIRST, THREE_STAR, TWO_STAR
}
